version 0.1.4-rc

diff --git a/lib/ftnlib b/lib/ftnlib
--- a/lib/ftnlib
+++ b/lib/ftnlib
@@ -8,19 +8,19 @@ ftn_base_list="@(checkrounds|accounts|depool|mode|help)"
 ftn_node_list="@(adnl|timediff)"
 msig_elector_list="@(electionlog|electionrun|extrastake|setstake|recover)"
 
-ftn_version="0.1.3-7 (alpha; unstable;)"
+ftn_version="0.1.4-rc"
 
 
 ##########
 # Common stuff
 
 function get_account {
-    if [ -z "${1}" ]; then
-        account=${FTN_ACCOUNT}
-    elif [ -r "$FTN_KEYS_DIR/${1}.addr" ]; then
-        account=$(cat $FTN_KEYS_DIR/${1}.addr)
-    elif [[ ${1} == *":"* ]]; then
-        account=${1}
+    if [ -z "$1" ]; then
+        account=$FTN_ACCOUNT
+    elif [ -r "$FTN_KEYS_DIR/$1.addr" ]; then
+        account=$(cat $FTN_KEYS_DIR/$1.addr)
+    elif [[ $1 == *":"* ]]; then
+        account=$1
     else
         echo "Error: can't recognize account ($1). The subcommand cannot be proceeded."
         exit 1
@@ -81,6 +81,7 @@ function mode {
 
 
 function checkrounds {
+    . $FTN_WRP/lib/ftnlibdepool
     num=$(dpl_getrounds "dpl_getrounds" | grep -n "Result:" | awk -F ':' '{print $1}')
     result="{$( dpl_getrounds | tail +$(($num+1)) )"
     declare -a rounds
@@ -152,15 +153,15 @@ function confirm {
     # $3 - Transactions ID
     if [ -z "$3" ]; then
         for trx in $(transactions | grep \"id\": | tr -d '",' | awk '{print $2}'); do
-            read -r -d '' PARAMS << EOF
+            read -r -d '' PARAMS << EOD || true
             {"transactionId":"$trx"}
-EOF
+EOD
             tonos call $FTN_ACCOUNT confirmTransaction $PARAMS: --abi $MULSIG_CONTRACT_DIR/SafeMultisigWallet.abi.json --sign $FTN_KEYS_DIR/$2 2>&1 | tee -a $FTN_LOG/$1.log
         done
     else
-        read -r -d '' PARAMS << EOF
+        read -r -d '' PARAMS << EOD || true
         "{"transactionId":"$3"}"
-EOF
+EOD
         tonos call $FTN_ACCOUNT confirmTransaction $PARAMS --abi $MULSIG_CONTRACT_DIR/SafeMultisigWallet.abi.json --sign $FTN_KEYS_DIR/$2 2>&1 | tee -a $FTN_LOG/$1.log
     fi
 }
@@ -174,12 +175,15 @@ function submit {
     # $5 - Payload   # Payload block
     get_account $2
     NANO=$(ftn convert $3)
-    echo $NANO
     test "$4" = "false" && isBounce="false" || isBounce="true"
-    read -r -d '' PARAMS << EOF
+    read -r -d '' PARAMS << EOD || true
     {"dest":"$account","value":"$NANO","bounce":"$isBounce","allBalance":"false","payload":"$5"}
-EOF
-    tonos call $FTN_ACCOUNT submitTransaction $PARAMS --abi $MULSIG_CONTRACT_DIR/SafeMultisigWallet.abi.json --sign $FTN_KEYS_DIR/msig.keys.json 2>&1 | tee -a $FTN_LOG/$1.log
+EOD
+    if test -r $FTN_KEYS_DIR/$DEFAULT_KEY; then
+        tonos call $FTN_ACCOUNT submitTransaction $PARAMS --abi $MULSIG_CONTRACT_DIR/SafeMultisigWallet.abi.json --sign $FTN_KEYS_DIR/$DEFAULT_KEY 2>&1 | tee -a $FTN_LOG/$1.log 
+    else
+        echo "singkey file not found"
+    fi
 }
 
 
@@ -235,7 +239,7 @@ function electionrun {
 function extrastake {
     if [ -z "$2" ]; then
         echo "Amount of extrastake is not given."
-        exit 0
+        exit 1
     fi
     elector_addr=$(cat $FTN_KEYS_DIR/elections/elector-addr-base64)
     EXT_STAKE=$2
